export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const HANDLE_CHANGE = "HANDLE_CHANGE";
export const CLEAR_VALUES = "CLEAR_VALUES";

export const SETUP_USER_BEGIN = "SETUP_USER_BEGIN";
export const SETUP_USER_SUCCESS = "SETUP_USER_SUCCESS";
export const SETUP_USER_ERROR = "SETUP_uSER_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";

export const CREATE_POST_BEGIN = "CREATE_POST_BEGIN";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_ERROR = "CREATE_POST_ERROR";

export const GET_POSTS_BEGIN = "GET_POSTS_BEGIN";
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";

export const GET_LIKEPOSTS_BEGIN = "GET_LIKEPOSTS_BEGIN";
export const GET_LIKEPOSTS_SUCCESS = "GET_LIKEPOSTS_SUCCESS";

export const POSTS_DETAIL_BEGIN = "POSTS_DETAIL_BEGIN";
export const POSTS_DETAIL_SUCCESS = "POSTS_DETAIL_SUCCESS";

export const POSTS_BEGIN_SUCCESS = "POST_BEGIN_SUCCESS";
export const POSTS_UPDATE_SUCCESS = "POSTS_UPDATE_SUCCESS";

export const POSTS_DELETE_BEGIN = "POST_DELETE_BEGIN";
export const POSTS_DELETE_SUCCESS = "POST_DELETE_SUCCESS";


export const LOADING_BEGIN = "LOADING_BEGIN";
export const GET_PROFILE_BEGIN = "GET_PROFILE_BEGIN";

export const FOLLOW_BEGIN = "FOLLOW_BEGIN";
export const FOLLOW_SUCCESS = "FOLLOW_SUCCESS";

export const UNFOLLOW_BEGIN = "UNFOLLOW_BEGIN";
export const UNFOLLOW_SUCCESS = "UNFOLLOW_SUCCESS";

export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_END = "SEARCH_END";


export const COMMENT_SUCCESS = "COMMENT_SUCCESS";
export const COMMENT_BEGIN = "COMMENT_BEGIN";
export const COMMENT_ERROR = "COMMENT_ERROR";


export const GET_COMMENTS_BEGIN = "GET_COMMENTS_BEGIN";
export const GET_COMMENTS_SUCCESS = "GET_COMMENTS_SUCCESS";
export const GET_COMMENTS_ERROR = "GET_COMMENTS_ERROR";


export const DELETE_COMMENT_BEGIN = "DELETE_COMMENT_BEGIN"
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_ERROR = "DELETE_COMMENT_ERROR";


export const UPDATE_COMMENT_BEGIN = "UPDATE_COMMENT_BEGIN";
export const UPDATE_COMMENT_SUCCESS = "UPDATE_COMMENT_SUCCESS";
export const UPDATE_COMMENT_ERROR = "UPDATE_COMMENT_ERROR";


export const UPDATE_PROFILE_BEGIN = "UPDATE_PROFILE_BEGIN";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_ERROR = "UPDATE_PROFILE_ERROR";

export const EXPLORE_BEGIN = "EXPLORE_BEGIN";
export const EXPLORE_SUCCESS = "EXPLORE_SUCCESS";
export const EXPLORE_ERROR = "UPDATE_PROFILE_ERROR";


export const CREATE_COLLECTION_BEGIN = "CREATE_COLLECTION_BEGIN";
export const CREATE_COLLECTION_SUCCESS = "CREATE_COLLECTION_SUCCESS";
export const CREATE_COLLECTION_ERROR = "CREATE_COLLECTION_ERROR";




export const UPDATE_COLLECTION_BEGIN = "UPDATE_COLLECTION_BEGIN";
export const UPDATE_COLLECTION_SUCCESS = "UPDATE_COLLECTION_SUCCESS";
export const UPDATE_COLLECTION_ERROR = "UPDATE_COLLECTION_ERROR";


export const GET_COLLECTION_BEGIN = "GET_COLLECTION_BEGIN";
export const GET_COLLECTION_SUCCESS = "GET_COLLECTION_SUCCESS";
export const GET_COLLECTION_ERROR = "GET_COLLECTION_ERROR";



export const REMOVE_COLLECTION_BEGIN = "REMOVE_COLLECTION_BEGIN";
export const REMOVE_COLLECTION_SUCCESS = "REMOVE_COLLECTION_SUCCESS";
export const REMOVE_COLLECTION_ERROR = "REMOVE_COLLECTION_ERROR";


export const SPECIFIC_COLLECTION_BEGIN = "SPECIFIC_COLLECTION_BEGIN";
export const SPECIFIC_COLLECTION_SUCCESS = "SPECIFIC_COLLECTION_SUCCESS";
export const SPECIFIC_COLLECTION_ERROR = "SPECIFIC_COLLECTION_ERROR";



export const ADD_SHORTS_BEGIN = "ADD_SHORTS_BEGIN";
export const ADD_SHORTS_SUCCESS = "ADD_SHORTS_SUCCESS";
export const ADD_SHORTS_ERROR = "ADD_SHORTS_ERROR";


export const LIKE_SHORTS_BEGIN = "LIKE_SHORTS_BEGIN";
export const LIKE_SHORTS_SUCCESS = "LIKE_SHORTS_SUCCESS";
export const LIKE_SHORTS_ERROR = "LIKE_SHORTS_ERROR";


export const SPECIFIC_PROFILE_BEGIN = "SPECIFIC_PROFILE_BEGIN";
export const SPECIFIC_PROFILE_SUCCESS = "SPECIFIC_PROFILE_SUCCESS";
export const SPECIFIC_PROFILE_ERROR = "SPECIFIC_PROFILE_ERROR";


export const DELETE_SHORTS_BEGIN = "DELETE_SHORTS_BEGIN";
export const DELETE_SHORTS_SUCCESS = "DELETE_SHORTS_SUCCESS";
export const DELETE_SHORTS_ERROR = "DELETE_SHORTS_ERROR";

