export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const HANDLE_CHANGE = "HANDLE_CHANGE";
export const CLEAR_VALUES = "CLEAR_VALUES";

export const SETUP_USER_BEGIN = "SETUP_USER_BEGIN";
export const SETUP_USER_SUCCESS = "SETUP_USER_SUCCESS";
export const SETUP_USER_ERROR = "SETUP_uSER_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";

export const CREATE_POST_BEGIN = "CREATE_POST_BEGIN";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_ERROR = "CREATE_POST_ERROR";

export const GET_POSTS_BEGIN = "GET_POSTS_BEGIN";
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";

export const GET_LIKEPOSTS_BEGIN = "GET_LIKEPOSTS_BEGIN";
export const GET_LIKEPOSTS_SUCCESS = "GET_LIKEPOSTS_SUCCESS";

export const POSTS_DETAIL_BEGIN = "POSTS_DETAIL_BEGIN";
export const POSTS_DETAIL_SUCCESS = "POSTS_DETAIL_SUCCESS";

export const POSTS_BEGIN_SUCCESS = "POST_BEGIN_SUCCESS";
export const POSTS_UPDATE_SUCCESS = "POSTS_UPDATE_SUCCESS";

export const POSTS_DELETE_BEGIN = "POST_DELETE_BEGIN";

export const LOADING_BEGIN = "LOADING_BEGIN";
export const GET_PROFILE_BEGIN = "GET_PROFILE_BEGIN";

export const FOLLOW_BEGIN = "FOLLOW_BEGIN";
export const FOLLOW_SUCCESS = "FOLLOW_SUCCESS";

export const UNFOLLOW_BEGIN = "UNFOLLOW_BEGIN";
export const UNFOLLOW_SUCCESS = "UNFOLLOW_SUCCESS";





